### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by etrigan63** [leftwm/leftwm-theme#13]
I am getting an error trying to build leftwm-theme. The error is:

error: no override and no default toolchain set

This happens in both the AUR and directly from Github.

I am using the command specified in the instructions:

carlos build --release

**Comment by mautamu** [comment]
Sounds like you need to `cargo +stable build --release` (Or nightly/beta if you have one of those installed). ~~We should consider adding default-toolchain file though~~

See https://rust-lang.github.io/rustup/overrides.html

**Comment by mautamu** [comment]
Closing this for now; if the issue persists please re-open.
