### ISSUE TITLE
Instructions.

### ISSUE THREAD

**Issue by dariusity** [leftwm/leftwm-theme#3]
There are no instructions available on how to install this.

**Comment by mautamu** [comment]
Good morning @dariusity, thanks for pointing that out! Forgot to make a new PR. Here is the current installation process:

Currently, LeftWM-theme is only available by Git. To install, clone this repository:
```bash
git clone https://github.com/leftwm/leftwm-theme
```
Then enter the repository: 
```
cd leftwm-theme
```
Then build with Cargo (Nightly Rust is required, use `rustup install nightly` or see [the rustup website.](https://doc.rust-lang.org/nightly/edition-guide/rust-2018/rustup-for-managing-rust-versions.html)):
```bash
cargo build --release
```
You can then install LeftWM-theme:
```bash
# for single-user install
cargo install
#-- or --
#for system-wide install
sudo cargo install --root=/usr/bin 
```

Please let me know if this process doesn't complete successfully for you so that we can fix any errors present.

**Comment by dariusity** [comment]
Hello, thanks for the reply. I will be very grateful if you can add the package to AUR? Or can I just create the PKGBUILD according to your instructions in your previous post to create a package for leftwm-theme? Cheers.

**Comment by mautamu** [comment]
I have added a -git package to the AUR:

https://aur.archlinux.org/packages/leftwm-theme-git/

~~You may need to install nightly rust: `rustup install nightly` first, not entirely sure.~~

Edit: I have removed nightly requirement with b2bf0b5. Will update the AUR package when #4 closes.

**Comment by dariusity** [comment]
Will you just please, leave some tips and hints on README? There is no right clicks, no menus, no visual, nothing but a mouse cursor. Are you for real? 

And you created a theme manager without saying how or where to get the themes!

**Comment by mautamu** [comment]
Please see https://github.com/mautamu/leftwm-theme/blob/master/README.md 

The general gist though is:
```bash
leftwm-theme update
leftwm-theme search (theme name) # optional, just lists themes with similar names
leftwm-theme install (theme name)
leftwm-theme apply (theme name)
```

The list of themes available in the default repository are available at https://github.com/leftwm/leftwm-community-themes and will be listed by `leftwm-theme update`

May I ask what do you mean by "nothing but a mouse cursor"?

**Comment by mautamu** [comment]
Following up on this - did you get this to work properly @dariusity? Is there something else that we ought to add in?

**Comment by dariusity** [comment]
Yes sorreh I have gone through the --help and got it working. At the moment it's just you with the repository for themes? I'd like to help out but I don't know liquid. 😭

**Comment by dariusity** [comment]
Yes sorreh I have gone through the --help and got it working. At the moment it's just you with the repository for themes? I'd like to help out but I don't know liquid. 😭
