### ISSUE TITLE
ERROR leftwm_theme > Operation did not complete successfully

### ISSUE THREAD

**Issue by dmarichuk** [leftwm/leftwm-theme#36]
Using Linux Mint, I tried to follow installation instruction. After I had installed LeftWM-theme with command `sudo install -s -Dm755 ./target/release/leftwm-theme -t /usr/bin` I tried to update it but got "Operation did not complete successfully". The issue was that I didn't have leftwm/ directory in ~/.config/. After creating it no errors occured

**Comment by mautamu** [comment]
Good afternoon, fellow adventurer!

Thank you for reporting this regression! I have submitted a PR to resolve this; leftwm-theme should now attempt to create the directory when it attempts to load the themes.toml file. Would you mind testing this if you have the opportunity?

Best,
Mau
