### ISSUE TITLE
Feature request : leftwm-theme uninstall xxxx --noconfirm

### ISSUE THREAD

**Issue by arcolinuxz** [leftwm/leftwm-theme#41]
Could you consider making an option to remove the manual yes to uninstall a theme?

I have been making themes and will probably make more.

I like to run a script that uninstalls and installs themes without the intervention of a human being. (yes/no)

I thought about pacman and its --noconfirm switch

![noconfirm](https://user-images.githubusercontent.com/36679406/139591690-a1c138d2-1558-4ca7-b77b-309049ad81b7.png)

**Comment by mautamu** [comment]
This sounds like a great idea!

**Comment by arcolinuxz** [comment]
thanks working just fine
https://youtu.be/OTNd4l8-0_Q
