### ISSUE TITLE
Void linux cargo build Fail

### ISSUE THREAD

**Issue by sithicas** [leftwm/leftwm-theme#43]
Just wanted to post this if it warrants. This could be a rust version issue on my end? (rustc 1.53.0)

Compiling clap v3.0.0-beta.5
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/sithicas/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.5/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by mautamu** [comment]
Howdy, fellow adventurer!

Rust 1.53.0 appears to be below Clap's [MSRV](https://github.com/clap-rs/clap#minimum-supported-version-of-rust-msrv). If you update to 1.56.1 (current stable) or anything >= 1.54.0, the error *should* go away. 

Best,
Mautamu

**Comment by sithicas** [comment]
Will do. Will go ahead and close this ticket and if it happens again with the upgraded Rust. I’ll revisit it. 

Thanks!

**Comment by mautamu** [comment]
Awesome possum! If something more recent fails, please let us know!
