### ISSUE TITLE
Manual install instructions

### ISSUE THREAD

**Issue by bmclean2** [leftwm/leftwm-theme#5]
In the manual system-wide install instructions `cargo install --root=/usr/bin` didn't work. I had to use `cargo install --root /usr --path <path to repo directory>` (I actually used `--root /usr/local`)  once cd'ing into the cloned directory. So the syntax should exclude `=` and remove the `/bin` and, at least for me, it would not install without `--path`.

**Comment by mautamu** [comment]
Ah, so it should be something akin to
 ```bash
sudo cargo install --path $(pwd) --root /usr/
```
?

Probably ought to copy the leftwm documentation and use
```
# General Builds
sudo install -s -Dm755 ./target/release/leftwm-theme -t /usr/bin
# Developer
sudo ln -s "$(pwd)"/target/release/leftwm-theme /usr/bin/leftwm-theme
```

**Comment by bmclean2** [comment]
> Ah, so it should be something akin to
> 
> ```shell
> sudo cargo install --path $(pwd) --root /usr/
> ```
> 
> ?

Yes

> 
> Probably ought to copy the leftwm documentation and use
> 
> ```
> # General Builds
> sudo install -s -Dm755 ./target/release/leftwm-theme -t /usr/bin
> # Developer
> sudo ln -s "$(pwd)"/target/release/leftwm-theme /usr/bin/leftwm-theme
> ```

Agreed. Just tried this for general builds and can confirm it works.

**Comment by mautamu** [comment]
Awesome! Thank you for calling attention to this! I will try to get around to fixing this tomorrow and checking the PKGBUILD to make sure it uses the right method as well.

**Comment by bmclean2** [comment]
Thanks! Also, just so you're aware, when I try to do the PKGBUILD on yay I get the following error `error: no such subcommand: '+nightly'`

**Comment by mautamu** [comment]
I have submitted a new PKGBUILD to the AUR which shouldn't require the +nightly flag, hopefully it works! Thank you again for calling these two issues to attention!
