### ISSUE TITLE
Error regarding `theme is incompatible with the installed version of LeftWM`

### ISSUE THREAD

**Issue by pranaypratyush** [leftwm/leftwm-theme#51]
```
> leftwm-theme apply "Blue Coffee"
Setting Blue Coffee as default theme.
 ERROR leftwm_theme::operations::apply > This theme is incompatible with the installed version of LeftWM.
 ERROR leftwm_theme::operations::apply > Not all prerequirements passed
 ERROR leftwm_theme                    > Operation did not complete successfully
```

I tried with multiple versions of leftwm.

**Comment by mautamu** [comment]
Which versions did you try? Blue Coffee doesn’t have the patches for the mainline 0.3.0-rc# branch yet, but there is a workaround to convince leftwm-theme that it’s okay when it’s not. Edit ~/.config/leftwm/known.toml and under the leftwm_version for blue coffee, clear it to be “”

**Comment by mautamu** [comment]
Closing per #55; feel free to reopen if you still cannot resolve.
