### ISSUE TITLE
Update theme incompatibility language and don't list unusable themes

### ISSUE THREAD

**Issue by copypasteonly** [leftwm/leftwm-theme#54]
When running `leftwm-theme apply Catppuccin` three rrors appear mainly
> This theme is incompatible with the installed version of LeftWM.
> Not all prerequirements passed
> Operation did not complete successfully

I just installed leftwm in a vm, no changes were made to the config file.Picom, dmenu, rofi, and polybar are installed.

**Comment by mautamu** [comment]
Hello, try updating now that leftwm-community-themes's file list is updated. If it persists, this error is intentional as the theme is not compatible with the version of leftwm you're using. 

To bring it up to compatibility, it will likely need a rewrite of the theme's shell scripts, namely `up` and `down`, to use leftwm-command rather than commands.pipe.

**Comment by copypasteonly** [comment]
> Hello, try updating now that leftwm-community-themes's file list is updated. If it persists, this error is intentional as the theme is not compatible with the version of leftwm you're using.
> 
> To bring it up to compatibility, it will likely need a rewrite of the theme's shell scripts, namely `up` and `down`, to use leftwm-command rather than commands.pipe.

Hello thank you so much, I only tried Catppuccin and didnt try others lol other themes are working. By the way should i still put dunst, picom, feh etc. on my .xinitrc since from what I can see it's already being called in the up file and I'm going to assume that my .xinitrc is getting executed first before the up file. Thanks!

**Comment by mautamu** [comment]
I'm not certain about the order of execution, but I believe you're correct that .xinitrc and autostart go first.

**Comment by mautamu** [comment]
The current error messages are not super helpful, it would be more useful to:
- [x] De-list themes (or denote themes) that are not usable with the currently installed leftwm (tracking: https://github.com/leftwm/leftwm-theme/issues/53)
- [x] Update the error message to convey that the error is not necessarily the end-all be all, the theme just needs updated. Perhaps create a wiki page of how to migrate versions?
