### ISSUE TITLE
Update not Work

### ISSUE THREAD

**Issue by velan001** [leftwm/leftwm-theme#65]
Leftwm-theme update command not work comes with Error

**Comment by VuiMuich** [comment]
Which error do you get?

(Will transfer to the `leftwm-theme` repo as it belongs there, later when I'm back on my desktop.)

**Comment by velan001** [comment]
> Which error do you get?
> 
> (Will transfer to the `leftwm-theme` repo as it belongs there, later when I'm back on my desktop.)
![oie_Bmw8NEoW9tVS](https://user-images.githubusercontent.com/124013073/228897784-fb50bad5-c78a-4468-916f-ccf6863fd801.png)
i didn't know what the error may be the repo make issue . The installation has no error.

**Comment by VuiMuich** [comment]
As mentioned earlier, this belongs more to this repo, then the `leftwm` core repo.

Is it possible, that for some reason the server is blocked or not avaelable?

**Comment by velan001** [comment]
> As mentioned earlier, this belongs more to this repo, then the `leftwm` core repo.
> 
> Is it possible, that for some reason the server is blocked or not avaelable?

I think it is blocked. I will use Torctl tool and I Run the update command. everything properly works.

**Comment by VuiMuich** [comment]
Then I guess the issue is out of the scope of this repository.
Gonna close.
